-- Create "dm_conversations" table
CREATE TABLE "public"."dm_conversations" ("id" uuid NOT NULL, "server_id" uuid NOT NULL, "user_low" uuid NOT NULL, "user_high" uuid NOT NULL, "last_message_at" timestamptz NULL, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, "created_by" uuid NOT NULL, "updated_by" uuid NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "dm_conversations_server_id_fkey" FOREIGN KEY ("server_id") REFERENCES "public"."servers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "dm_conversations_user_high_fkey" FOREIGN KEY ("user_high") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "dm_conversations_user_low_fkey" FOREIGN KEY ("user_low") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "chk_dm_conversations_user_order" CHECK (user_low < user_high));
-- Create index "idx_dm_conversations_uk_01" to table: "dm_conversations"
CREATE UNIQUE INDEX "idx_dm_conversations_uk_01" ON "public"."dm_conversations" ("server_id", "user_low", "user_high");
-- Create "dm_conversation_states" table
CREATE TABLE "public"."dm_conversation_states" ("conversation_id" uuid NOT NULL, "user_id" uuid NOT NULL, "server_id" uuid NOT NULL, "peer_user_id" uuid NOT NULL, "last_read_message_id" uuid NULL, "last_read_at" timestamptz NULL, "last_message_at" timestamptz NULL, "last_message_preview" text NULL, "unread_count" integer NOT NULL DEFAULT 0, "created_at" timestamptz NOT NULL, "updated_at" timestamptz NOT NULL, PRIMARY KEY ("conversation_id", "user_id"), CONSTRAINT "dm_conversation_states_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."dm_conversations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "dm_conversation_states_server_id_fkey" FOREIGN KEY ("server_id") REFERENCES "public"."servers" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "dm_conversation_states_user_id_fkey" FOREIGN KEY ("user_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_dm_conversation_states_pk_01" to table: "dm_conversation_states"
CREATE INDEX "idx_dm_conversation_states_pk_01" ON "public"."dm_conversation_states" ("user_id", "server_id", "last_message_at" DESC, "conversation_id" DESC);
-- Create "dm_messages" table
CREATE TABLE "public"."dm_messages" ("id" uuid NOT NULL, "conversation_id" uuid NOT NULL, "sender_id" uuid NOT NULL, "type" text NOT NULL DEFAULT 'text', "content" text NOT NULL, "client_message_id" uuid NOT NULL, "created_at" timestamptz NOT NULL, PRIMARY KEY ("id"), CONSTRAINT "dm_messages_conversation_id_fkey" FOREIGN KEY ("conversation_id") REFERENCES "public"."dm_conversations" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "dm_messages_sender_id_fkey" FOREIGN KEY ("sender_id") REFERENCES "public"."users" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
-- Create index "idx_dm_messages_pk_01" to table: "dm_messages"
CREATE INDEX "idx_dm_messages_pk_01" ON "public"."dm_messages" ("conversation_id", "created_at" DESC, "id" DESC);
-- Create index "idx_dm_messages_uk_01" to table: "dm_messages"
CREATE UNIQUE INDEX "idx_dm_messages_uk_01" ON "public"."dm_messages" ("conversation_id", "sender_id", "client_message_id");
