apiVersion: 1

datasources:
  - name: VictoriaMetrics
    type: prometheus
    uid: victoriametrics
    access: proxy
    url: http://victoria:8428
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "10s"
      httpMethod: POST

  - name: Tempo
    type: tempo
    uid: tempo
    access: proxy
    url: http://tempo:3200
    editable: true
    jsonData:
      tracesToLogs:
        datasourceUid: 'loki'
        filterByTraceID: true
        mapTagNamesEnabled: true
      serviceMap:
        datasourceUid: 'victoriametrics'
      search:
        filters:
          - id: service-name
            tag: service_name
            type: contains

  - name: Loki
    type: loki
    uid: loki
    access: proxy
    url: http://loki:3100
    editable: true
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: "trace_id=\"?([0-9a-f]+)\"?"
          name: TraceID
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
