apiVersion: 1

deleteDatasources:
  - name: prometheus

datasources:
  - name: prometheus
    type: prometheus
    uid: prometheus
    url: http://prometheus:9090
    access: proxy
    isDefault: true
    jsonData:
      httpMethod: POST
      timeInterval: 15s
