apiVersion: 1

deleteDatasources:
  - name: Tempo
  - name: tempo

datasources:
  - name: Tempo
    type: tempo
    uid: tempo
    url: http://tempo:3200
    access: proxy
    editable: true
    jsonData:
      httpMethod: GET
      tracesToLogsV2:
        datasourceUid: loki
        spanStartTimeShift: "-2s"
        spanEndTimeShift: "2s"
        filterByTraceID: true
        filterBySpanID: false
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: loki
