package shared

const MAX_IMAGE_SIZE = 5 * 1024 * 1024

const MAX_IMAGE_SIZE_FREE = 10 * 1024 * 1024
const MAX_IMAGE_SIZE_PLUS = 100 * 1024 * 1024
const MAX_VIDEO_SIZE_FREE = 50 * 1024 * 1024
const MAX_VIDEO_SIZE_PLUS = 100 * 1024 * 1024

const MAX_VIDEO_SIZE = 100 * 1024 * 1024

const PLUS_PRICE_IDR int64 = 50000
const PLUS_TAX_PERCENT int64 = 11
const PLUS_DURATION_DAYS = 30
const MAX_VIDEO_DURATION = 180
const MAX_IMAGE_WIDTH = 1080
const MIN_ASPECT_RATIO = 0.8
const MAX_ASPECT_RATIO = 1.91

const DEFAULT_LIMIT = 10
const MAX_LIMIT = 20
const MIN_SEARCH_QUERY_LENGTH = 2
const MAX_SEARCH_QUERY_LENGTH = 100
const DEFAULT_MAX_MEMORY int64 = 110 << 20
const PLATFORM_ANDROID = "android"
const PLATFORM_IOS = "ios"

const DEFAULT_USER_SETTINGS = `{"notif_like":true,"notif_comment":true,"notif_reply":true}`

const (
	ERR_BAD_REQUEST_CODE                = "BAD_REQUEST_ERROR"
	ERR_VALIDATION_CODE                 = "VALIDATION_ERROR"
	ERR_INVALID_REQUEST_BODY_ERROR_CODE = "INVALID_REQUEST_BODY_ERROR"
	ERR_INVALID_CONTENT_TYPE_MESSAGE    = "Invalid Content-Type header. Endpoint requires multipart/form-data."
	ERR_INVALID_REQUEST_BODY_MESSAGE    = "The request is invalid or malformed"

	ERR_UPLOAD_SIZE_EXCEEDED_CODE = "UPLOAD_SIZE_EXCEEDED_ERROR"

	ERR_INTERNAL_SERVER_ERROR_CODE    = "INTERNAL_SERVER_ERROR"
	ERR_INTENRAL_SERVER_ERROR_MESSAGE = "Something went wrong. If the problem persists, please contact support"

	ERR_UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR"
	ERR_UNAUTHORIZED_CODE  = "UNAUTHORIZED_ERROR"
	ERR_NOT_FOUND_ERROR    = "NOT_FOUND_ERROR"
	ERR_NOT_FOUND_CODE     = "NOT_FOUND_ERROR"
	ERR_FORBIDDEN_CODE     = "FORBIDDEN_ERROR"
	ERR_DUPLICATE_CODE     = "DUPLICATE_ERROR"
	ERR_CONFLICT_CODE      = "CONFLICT_ERROR"
)
