apiVersion: 1

deleteDatasources:
  - name: Loki
  - name: loki

datasources:
  - name: Loki
    type: loki
    uid: loki
    url: http://loki:3100
    access: proxy
    isDefault: false
    editable: true
    jsonData:
      derivedFields:
        - name: TraceID
          matcherType: label
          matcherRegex: trace_id
          url: "${__value.raw}"
          urlDisplayLabel: View Trace in Tempo
          datasourceUid: tempo
          internalLink: true
